import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { getCoverUrl } from '../data/books';

function BookDetails({ books }) {
  const { id } = useParams();
  const book = books?.find(b => b.id === parseInt(id));

  // Inicializa comentários do LocalStorage ou carrega os iniciais se for livro do Mock
  const [comments, setComments] = useState(() => {
    const saved = localStorage.getItem(`comments_${id}`);
    if (saved) return JSON.parse(saved);
    
    // Default para livros do mock (IDs baixos)
    if (book && book.id < 1700000000000) {
      return [
        { id: 1, name: "John Doe", text: "Incredible world building!", rating: 5, likes: 12, date: "2026-02-15" },
        { id: 2, name: "Jane Smith", text: "A bit slow but deep.", rating: 4, likes: 5, date: "2026-02-20" }
      ];
    }
    return [];
  });

  const [newName, setNewName] = useState('');
  const [newComment, setNewComment] = useState('');
  const [selectedRating, setSelectedRating] = useState(0);
  const [filter, setFilter] = useState('relevant');

  // Persiste os comentários no LocalStorage sempre que houver mudança
  useEffect(() => {
    if (id) {
      localStorage.setItem(`comments_${id}`, JSON.stringify(comments));
    }
  }, [comments, id]);

  if (!book) return <div className="text-center p-20 text-white font-special text-2xl">Book not found!</div>;

  const communityAverage = comments.length > 0 
    ? (comments.reduce((acc, curr) => acc + curr.rating, 0) / comments.length).toFixed(1)
    : "0.0";

  const handleAddComment = (e) => {
    e.preventDefault();
    if (!newName || selectedRating === 0) {
      alert("Please provide your name and a rating!");
      return;
    }

    const newEntry = {
      id: Date.now(),
      name: newName,
      text: newComment,
      rating: selectedRating,
      likes: 0,
      date: new Date().toISOString().split('T')[0]
    };

    setComments([newEntry, ...comments]);
    setNewName('');
    setNewComment('');
    setSelectedRating(0);
  };

  const handleLike = (commentId) => {
    setComments(prevComments => 
      prevComments.map(c => c.id === commentId ? { ...c, likes: c.likes + 1 } : c)
    );
  };

  const sortedComments = [...comments].sort((a, b) => {
    if (filter === 'relevant') return b.likes - a.likes;
    return new Date(b.date) - new Date(a.date);
  });

  return (
    <div className="max-w-5xl w-full mt-10 p-4 md:p-10 flex flex-col gap-10 text-white">
      
      {/* SEÇÃO PRINCIPAL */}
      <div className="w-full bg-slate-900 rounded-2xl shadow-2xl flex flex-col md:flex-row gap-10 border border-slate-800 p-8">
        <img src={getCoverUrl(book.isbn)} alt={book.title} className="w-64 h-96 object-cover rounded-lg shadow-2xl border border-slate-700" />
        
        <div className="flex flex-col flex-1 text-left">
          <div className="flex justify-between items-start mb-2">
            <h1 className="text-4xl font-bold">{book.title}</h1>
            <div className="bg-blue-600/20 border border-blue-500 text-blue-400 px-3 py-1 rounded-lg font-bold text-sm whitespace-nowrap">
              API SCORE: {book.rating || '0.0'} ★
            </div>
          </div>
          <p className="text-xl text-slate-400 mb-6 font-special">by {book.author}</p>

          <div className="bg-slate-800/50 p-6 rounded-xl mb-6 border border-slate-700/50">
            <h3 className="text-blue-500 font-bold uppercase text-[10px] tracking-widest mb-2">Book Summary</h3>
            <p className="text-slate-300 leading-relaxed italic font-special">
              "This summary will be automatically generated by our AI or fetched from the Spring Boot backend."
            </p>
          </div>

          <div className="grid grid-cols-2 gap-4 mt-auto">
            <div className="bg-slate-800 p-3 rounded-lg border border-slate-700/30">
              <p className="text-slate-500 text-[10px] uppercase font-bold">Community Rating</p>
              <p className="text-2xl font-black">{communityAverage} <span className="text-blue-500 text-lg">★</span></p>
            </div>
            <div className="bg-slate-800 p-3 rounded-lg border border-slate-700/30">
              <p className="text-slate-500 text-[10px] uppercase font-bold">Total Reviews</p>
              <p className="text-2xl font-black">{comments.length}</p>
            </div>
          </div>
        </div>
      </div>

      {/* SEÇÃO DE REVIEWS */}
      <div className="w-full max-w-4xl mx-auto flex flex-col gap-8">
        <div className="flex justify-between items-center border-b border-slate-800 pb-4">
          <h2 className="text-2xl font-bold uppercase tracking-tighter">User Discussion</h2>
          <select value={filter} onChange={(e) => setFilter(e.target.value)} className="bg-slate-900 text-slate-400 text-xs border border-slate-700 rounded px-2 py-1 outline-none cursor-pointer">
            <option value="relevant">Most Relevant</option>
            <option value="recent">Most Recent</option>
          </select>
        </div>

        {/* FORMULÁRIO */}
        <form onSubmit={handleAddComment} className="bg-slate-900 border border-slate-800 p-6 rounded-xl flex flex-col gap-5 shadow-xl">
          <div className="flex flex-col md:flex-row gap-4">
            <input 
              type="text" placeholder="Your Name" 
              className="flex-1 bg-slate-800 border border-slate-700 rounded-lg p-3 text-white outline-none focus:border-blue-500"
              value={newName} onChange={(e) => setNewName(e.target.value)} required
            />
            <div className="flex items-center gap-2 bg-slate-800 px-4 py-2 rounded-lg border border-slate-700">
              <span className="text-slate-400 text-xs uppercase font-bold mr-2">Rate:</span>
              {[1, 2, 3, 4, 5].map((num) => (
                <button 
                  key={num} type="button" 
                  onClick={() => setSelectedRating(num)}
                  className={`text-xl transition-all cursor-pointer ${selectedRating >= num ? 'text-blue-500' : 'text-slate-600'}`}
                >
                  ★
                </button>
              ))}
            </div>
          </div>
          <textarea 
            placeholder="Write your review here..." rows="3"
            className="bg-slate-800 border border-slate-700 rounded-lg p-3 text-white outline-none focus:border-blue-500 resize-none"
            value={newComment} onChange={(e) => setNewComment(e.target.value)}
          ></textarea>
          <button type="submit" className="bg-blue-600 hover:bg-blue-500 text-white font-bold py-3 rounded-lg transition-all self-end px-12 uppercase text-xs tracking-widest shadow-lg cursor-pointer">
            Post Review
          </button>
        </form>

        {/* LISTAGEM */}
        <div className="flex flex-col gap-6">
          {sortedComments.length > 0 ? (
            sortedComments.map(c => (
              <div key={c.id} className="bg-slate-900 border border-slate-800 p-6 rounded-xl text-left border-l-4 border-l-blue-600">
                <div className="flex justify-between items-start mb-4">
                  <div>
                    <h4 className="text-white font-bold">{c.name}</h4>
                    <div className="text-blue-500 text-sm">
                      {"★".repeat(c.rating)}{"☆".repeat(5 - c.rating)}
                      <span className="text-slate-600 ml-2">({c.rating}/5)</span>
                    </div>
                  </div>
                  <span className="text-slate-600 text-[10px] font-special uppercase">{c.date}</span>
                </div>
                <p className="text-slate-300 leading-relaxed font-special">{c.text || <em>User only left a rating.</em>}</p>
                <div className="mt-4">
                   <button 
                    type="button"
                    onClick={() => handleLike(c.id)}
                    className="text-slate-500 hover:text-blue-400 text-xs flex items-center gap-1 transition-colors cursor-pointer"
                   >
                     👍 Helpful ({c.likes})
                   </button>
                </div>
              </div>
            ))
          ) : (
            <p className="text-center text-slate-600 italic py-10 font-special tracking-widest">No community reviews yet.</p>
          )}
        </div>
      </div>

      <Link to="/" className="mt-8 text-slate-500 hover:text-white transition-colors mb-10 text-center font-special uppercase text-xs tracking-widest">
        ← Back to Library
      </Link>
    </div>
  );
}

export default BookDetails;