import { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { getCoverUrl } from '../data/books';

function BookDetails({ books, onDeleteBook, onUpdateBook, isAdmin }) {
  const { id } = useParams();
  const navigate = useNavigate();
  const book = books?.find(b => b.id === parseInt(id));

  // Estados para Edição
  const [isEditing, setIsEditing] = useState(false);
  const [editTitle, setEditTitle] = useState(book?.title || "");
  const [editAuthor, setEditAuthor] = useState(book?.author || "");

  const [comments, setComments] = useState(() => {
    const saved = localStorage.getItem(`comments_${id}`);
    if (saved) return JSON.parse(saved);
    
    if (book && book.id < 1700000000000) {
      return [
        { id: 1, name: "John Doe", text: "Incredible world building!", rating: 5, likes: 12, date: "2026-02-15" },
        { id: 2, name: "Jane Smith", text: "A bit slow but deep.", rating: 4, likes: 5, date: "2026-02-20" }
      ];
    }
    return [];
  });

  const [newName, setNewName] = useState('');
  const [newComment, setNewComment] = useState('');
  const [selectedRating, setSelectedRating] = useState(0);
  const [filter, setFilter] = useState('relevant');

  useEffect(() => {
    if (id) {
      localStorage.setItem(`comments_${id}`, JSON.stringify(comments));
    }
  }, [comments, id]);

  if (!book) return <div className="text-center p-20 text-white font-special text-2xl font-bold tracking-widest uppercase">Book not found!</div>;

  const communityAverage = comments.length > 0 
    ? (comments.reduce((acc, curr) => acc + curr.rating, 0) / comments.length).toFixed(1)
    : "0.0";

  // --- FUNÇÃO PARA SALVAR EDIÇÃO ---
  const handleSaveEdit = () => {
    onUpdateBook(book.id, { title: editTitle, author: editAuthor });
    setIsEditing(false);
    alert("Book updated successfully!");
  };

  const handleConfirmDelete = () => {
    if (window.confirm("Are you sure you want to permanently remove this book?")) {
      const wasDeleted = onDeleteBook(book.id);
      if (wasDeleted) navigate('/');
    }
  };

  const handleAddComment = (e) => {
    e.preventDefault();
    if (!newName || selectedRating === 0) {
      alert("Please provide your name and a rating!");
      return;
    }
    const newEntry = {
      id: Date.now(),
      name: newName,
      text: newComment,
      rating: selectedRating,
      likes: 0,
      date: new Date().toISOString().split('T')[0]
    };
    setComments([newEntry, ...comments]);
    setNewName(''); setNewComment(''); setSelectedRating(0);
  };

  const handleLike = (commentId) => {
    setComments(prev => prev.map(c => c.id === commentId ? { ...c, likes: c.likes + 1 } : c));
  };

  const sortedComments = [...comments].sort((a, b) => {
    if (filter === 'relevant') return b.likes - a.likes;
    return new Date(b.date) - new Date(a.date);
  });

  return (
    <div className="max-w-5xl w-full mt-10 p-4 md:p-10 flex flex-col gap-10 text-white">
      
      {/* MAIN SECTION */}
      <div className="w-full bg-slate-900 rounded-2xl shadow-2xl flex flex-col md:flex-row gap-10 border border-slate-800 p-8">
        
        <img src={getCoverUrl(book.isbn)} alt={book.title} className="w-64 h-96 object-cover rounded-lg shadow-2xl border border-slate-700" />
        
        <div className="flex flex-col flex-1 text-left">
          <div className="flex justify-between items-start mb-2 gap-4">
            {isEditing ? (
              <input 
                className="bg-slate-800 border border-blue-500 rounded p-2 text-2xl font-bold w-full outline-none"
                value={editTitle}
                onChange={(e) => setEditTitle(e.target.value)}
              />
            ) : (
              <h1 className="text-4xl font-bold tracking-tight">{book.title}</h1>
            )}
            <div className="bg-blue-600/20 border border-blue-500 text-blue-400 px-3 py-1 rounded-lg font-bold text-sm whitespace-nowrap">
              API SCORE: {book.rating || '0.0'} ★
            </div>
          </div>

          {isEditing ? (
            <input 
              className="bg-slate-800 border border-slate-700 rounded p-1 text-lg mb-6 w-full outline-none text-slate-400 mt-2"
              value={editAuthor}
              onChange={(e) => setEditAuthor(e.target.value)}
            />
          ) : (
            <p className="text-xl text-slate-400 mb-6 font-special tracking-wide underline underline-offset-8 decoration-slate-800">by {book.author}</p>
          )}

          <div className="bg-slate-800/30 p-6 rounded-xl mb-6 border border-slate-700/50">
            <h3 className="text-blue-500 font-bold uppercase text-[10px] tracking-widest mb-2">Book Summary</h3>
            <p className="text-slate-300 leading-relaxed italic font-special">
              "This summary will be automatically generated by our AI or fetched from the Spring Boot backend."
            </p>
          </div>

          <div className="flex items-end justify-between gap-4 mt-auto">
            <div className="grid grid-cols-2 gap-4 flex-1">
              <div className="bg-slate-800/80 p-3 rounded-lg border border-slate-700/30">
                <p className="text-slate-500 text-[10px] uppercase font-bold tracking-widest mb-1">Community Rating</p>
                <p className="text-2xl font-black">{communityAverage} <span className="text-blue-500 text-lg">★</span></p>
              </div>
              <div className="bg-slate-800/80 p-3 rounded-lg border border-slate-700/30">
                <p className="text-slate-500 text-[10px] uppercase font-bold tracking-widest mb-1">Total Reviews</p>
                <p className="text-2xl font-black">{comments.length}</p>
              </div>
            </div>

            {/* ADMIN ACTIONS */}
            {isAdmin && (
              <div className="flex gap-2">
                {isEditing ? (
                  <button 
                    onClick={handleSaveEdit}
                    className="bg-blue-600 hover:bg-blue-500 text-white p-4 rounded-xl transition-all cursor-pointer font-bold uppercase text-[10px] tracking-widest"
                  >
                    Save Changes
                  </button>
                ) : (
                  <button 
                    onClick={() => setIsEditing(true)}
                    className="bg-slate-800 border border-slate-700 hover:border-blue-500 text-slate-400 hover:text-blue-500 transition-all cursor-pointer p-4 rounded-xl group"
                    title="Edit Book Details"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="group-hover:rotate-12 transition-transform">
                      <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
                      <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
                    </svg>
                  </button>
                )}
                
                <button 
                  onClick={handleConfirmDelete}
                  className="bg-red-950/30 border border-red-900/50 hover:bg-red-600 hover:text-white text-red-500 transition-all cursor-pointer p-4 rounded-xl group"
                  title="Remove from Library"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="group-hover:scale-110 transition-transform">
                    <path d="M3 6h18"></path>
                    <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"></path>
                    <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"></path>
                    <line x1="10" y1="11" x2="10" y2="17"></line>
                    <line x1="14" y1="11" x2="14" y2="17"></line>
                  </svg>
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* ... (resto do componente igual: Discussion Section e Back link) ... */}
      <div className="w-full max-w-4xl mx-auto flex flex-col gap-8">
        <div className="flex justify-between items-center border-b border-slate-800 pb-4">
          <h2 className="text-2xl font-bold uppercase tracking-tighter">User Discussion</h2>
          <select value={filter} onChange={(e) => setFilter(e.target.value)} className="bg-slate-900 text-slate-400 text-xs border border-slate-700 rounded px-2 py-1 outline-none cursor-pointer hover:border-slate-500 transition-colors">
            <option value="relevant">Most Relevant</option>
            <option value="recent">Most Recent</option>
          </select>
        </div>

        <form onSubmit={handleAddComment} className="bg-slate-900 border border-slate-800 p-6 rounded-xl flex flex-col gap-5 shadow-xl">
          <div className="flex flex-col md:flex-row gap-4">
            <input 
              type="text" placeholder="Your Name" 
              className="flex-1 bg-slate-800 border border-slate-700 rounded-lg p-3 text-white outline-none focus:border-blue-500 transition-all font-special"
              value={newName} onChange={(e) => setNewName(e.target.value)} required
            />
            <div className="flex items-center gap-2 bg-slate-800 px-4 py-2 rounded-lg border border-slate-700">
              <span className="text-slate-500 text-[10px] uppercase font-bold tracking-widest mr-2">Rate:</span>
              {[1, 2, 3, 4, 5].map((num) => (
                <button 
                  key={num} type="button" 
                  onClick={() => setSelectedRating(num)}
                  className={`text-xl transition-all cursor-pointer hover:scale-125 ${selectedRating >= num ? 'text-blue-500' : 'text-slate-700'}`}
                >
                  ★
                </button>
              ))}
            </div>
          </div>
          <textarea 
            placeholder="Write your review here..." rows="3"
            className="bg-slate-800 border border-slate-700 rounded-lg p-3 text-white outline-none focus:border-blue-500 resize-none font-special"
            value={newComment} onChange={(e) => setNewComment(e.target.value)}
          ></textarea>
          <button type="submit" className="bg-blue-600 hover:bg-blue-500 text-white font-bold py-3 rounded-lg transition-all self-end px-12 uppercase text-[10px] tracking-[4px] shadow-lg cursor-pointer active:scale-95">
            Post Review
          </button>
        </form>

        <div className="flex flex-col gap-6">
          {sortedComments.length > 0 ? (
            sortedComments.map(c => (
              <div key={c.id} className="bg-slate-900 border border-slate-800 p-6 rounded-xl text-left border-l-4 border-l-blue-600 hover:bg-slate-800/40 transition-colors group">
                <div className="flex justify-between items-start mb-4">
                  <div>
                    <h4 className="text-white font-bold tracking-wide">{c.name}</h4>
                    <div className="text-blue-500 text-sm">
                      {"★".repeat(c.rating)}{"☆".repeat(5 - c.rating)}
                      <span className="text-slate-600 ml-2 font-special text-xs">({c.rating}/5)</span>
                    </div>
                  </div>
                  <span className="text-slate-600 text-[10px] font-special uppercase tracking-widest">{c.date}</span>
                </div>
                <p className="text-slate-300 leading-relaxed font-special">{c.text || <em className="opacity-50 font-sans">User only left a rating.</em>}</p>
                <div className="mt-4">
                   <button 
                    type="button"
                    onClick={() => handleLike(c.id)}
                    className="text-slate-600 hover:text-blue-400 text-[10px] font-bold uppercase tracking-widest flex items-center gap-2 transition-colors cursor-pointer"
                   >
                     <span className="text-sm">👍</span> Helpful ({c.likes})
                   </button>
                </div>
              </div>
            ))
          ) : (
            <p className="text-center text-slate-700 italic py-10 font-special tracking-widest uppercase text-xs">No community reviews yet.</p>
          )}
        </div>
      </div>

      <Link to="/" className="mt-8 text-slate-600 hover:text-white transition-colors mb-10 text-center font-special uppercase text-[10px] tracking-[4px]">
        ← Back to Gallery
      </Link>
    </div>
  );
}

export default BookDetails;