# Nome do Projeto
spring.application.name=Readly

# Configuração do Banco de Dados H2 (Salvando em arquivo para não perder os dados)
spring.datasource.url=jdbc:h2:file:./data/readlydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=

# H2 Console (Para você conseguir ver a tabela no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false

# JPA / Hibernate (Cria as tabelas automaticamente baseado na classe Book)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
